### ISSUE TITLE
[BUG] College page showing too much white space

### ISSUE THREAD

**Issue by hsmint** [LatteCode/Frontend#14]
**Describe the bug**
Showing too much white space

**To Reproduce**
1. Go to '교내기관 안내'
2. Scroll down to the end
3. See error

**Expected behavior**
The page should have end on "학생회관" but showing too much white space

**Screenshots**
![image](https://user-images.githubusercontent.com/48782012/84591680-606a2180-ae7b-11ea-80a8-5aeb49693181.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL

**Additional context**

**Comment by CXZ7720** [comment]
![image](https://user-images.githubusercontent.com/29659112/85224152-1d6ff700-b403-11ea-86d6-513f3de555b9.png)

Because we overflowed each cards using `top: -000px,` `<div>` tags component has been go up few pixels. But, it seems that there are some problems in `<router-link>` tags. It doesn't go up like the `<div>` tags.

What if pop `<router-link>` out of `div` tags?
it would be like this.
```
<router-link :to="{ name: 'Info', params: { id: currentList } }">
    <div :key="idx" v-for="(currentList, idx) in currentList">
        <MenuBox :class="'box_'+(idx+1)" :imgPath="imgList[idx]" :textName="currentList"> 
        </MenuBox>
    </div>
</router-link>

```

**Comment by krumaska** [comment]
if pop <router-link> out of div tags, router-link did not working like below.
After clicking on Image, router-link link to `http://localhost:8080/`
